#%RAML 1.0
---
title: Adapter Bridge API for SEMaaS
version: 1.0
baseUri: http://localhost:3000/

documentation:
  - title: Adapter Bridge
    content: |
      Adapter Bridge API for SEMaaS.
/:
  displayName: Adapter Bridge API for SEMaaS
  get:
    description: |
      Adapter Bridge API for SEMaaS RAML
/event:
  displayName: Event
  post:
    description: |
      Send even to end point
    body:
      application/json:
        example: |
          {
            "stream" : "streamapx",
            "timestamp": "1495466076",
            "schema": "CARDPAYMENTEVENTDEMOMX1",
            "offset": 2,
            "data": {
              "strGroup": "MFADTDCANLS",
              "pageSize": 1,
              "pageNumber": 1,
              "codEstructura": 124
              }
          }
    responses:
      201:
        description: |
          The event has been succesfully sent
        body:
          application/json:
            example: |
              {
                "id": "c75e365e-3b1d-11e7-8efc-4fac2cb1a949",
                "transactionTime": "2017-05-17T16:27:55.297+00:00"
              }
            schema: !include schemas/acceptedResponse.json
      400:
        description: |
          Bad Request Error
        body:
          application/json:
            example: |
              {
                "id": "1495737322532-BJXe4jVZ-",
                "transactionTime": "2016-08-25T12:09:30.644+00:00",
                "errors": [
                  {
                    "code": "clientError",
                    "description": "Unsupported content-type header \"text/plain\", expected \"application/json\""
                  }
                ]
              }
            schema: !include schemas/clientErrorResponse.json
      500:
        description: |
          Internal Server Error
        body:
          application/json:
            example: |
              {
                "id": "1495737322532-BJXe4jVZ-",
                "transactionTime": "2016-08-25T12:09:30.644+00:00",
                "errors": [
                  {
                  "code": "internal_error",
                  "description": "The server encountered an unexpected condition"
                  }
                ]
              }
            schema: !include schemas/serverErrorResponse.json
      502:
        description: |
          Bad Gateway
        body:
          application/json:
            example: |
              {
                "id": "1495737322532-BJXe4jVZ-",
                "transactionTime": "2016-08-25T12:09:30.644+00:00",
                "errors": [
                  {
                  "code": "gateway",
                  "description": "The server received an invalid response"
                  }
                ]
              }
            schema: !include schemas/serverErrorResponse.json
      504:
        description: |
          Gateway Time-out
        body:
          application/json:
            example: |
              {
                "id": "1495737322532-BJXe4jVZ-",
                "transactionTime": "2016-08-25T12:09:30.644+00:00",
                "errors": [
                  {
                  "code": "timeout",
                  "description": "The server did not receive a timely response"
                  }
                ]
              }
            schema: !include schemas/serverErrorResponse.json
