'use strict';

const NOTIFICATION_TYPE = 'MAIL';
const DATETIME_FORMAT = 'YYYY-MM-DDTHH:mm:ss.SSSZ';
const DATE_FORMAT = 'YYYY-MM-DD';
const DELIVERY_SCHEDULED_TIME_FORMAT = 'YYYY-MM-DDTHH:mm';
const CHARACTER_SEPARATOR = '^';
const COLON               = ':';

const ERROR_TYPE = {
  CLIENT: 'CLIENT_ERROR',
  SERVER: 'SERVER_ERROR',
  EXTERNAL: 'EXTERNAL_ERROR'
};

const NOTIFICATION_STATE = {
  DISCARDED : 'DISCARDED',
  ACCEPTED  : 'ACCEPTED',
  REJECTED  : 'REJECTED',
  SCHEDULED : 'SCHEDULED',
  DELIVERED : 'DELIVERED',
  ERROR     : 'ERROR',
  INVALID   : 'INVALID'
};

const HTTP_CODE = {
  ACCEPTED: '202',
  CLIENT_ERROR: '400',
  SERVER_ERROR: '500',
  EXTERNAL_ERROR: '502'
};

exports.NOTIFICATION_TYPE = NOTIFICATION_TYPE;
exports.DATE_FORMAT = DATE_FORMAT;
exports.DATETIME_FORMAT = DATETIME_FORMAT;
exports.DELIVERY_SCHEDULED_TIME_FORMAT = DELIVERY_SCHEDULED_TIME_FORMAT;
exports.CHARACTER_SEPARATOR = CHARACTER_SEPARATOR;
exports.COLON = COLON;

exports.ERROR_TYPE = ERROR_TYPE;
exports.NOTIFICATION_STATE = NOTIFICATION_STATE;
exports.HTTP_CODE = HTTP_CODE;
